server:
  port: 8080
teacher:
  id: 1
  name: tom
  age: 18
  sex: 男  
spring:
  datasource: 
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://localhost:3306/springboot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
